### PR TITLE
some improvements

### PR DESCRIPTION
**Pull request by vineelsai26**
Fixed issue #9 and some other improvements

### CODE REVIEW

**Comment by TathagataRoy1278** [comment]
Thank you!
There is just one thing, is there a way you can check if the system is running x-terminal-emulator or gnome or something else before running the command?
And also put config.py in .gitignore?

**Comment by vineelsai26** [comment]
x-terminal-emulator command opens default terminal in your system

**Comment by TathagataRoy1278** [comment]
Sorry! my bad

**Comment by TathagataRoy1278** [comment]
@vineelsai26 fixed some things from #17 in the latest commit, just check it out

**Pull request merged**
